version: "3"

services:
  sms-backend:
    image: node:12
    container_name: sms-backend
    expose:
      - "4000"
    ports:
      - "4000:4000"
    user: node
    volumes:
      - ./packages/backend:/home/node/app
    command: bash -c 'yarn && yarn start'
  sms-frontend:
    image: node:12
    container_name: sms-frontend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./packages/frontend:/home/node/app
    command: bash -c 'yarn && yarn start'
  # sms-nginx:
  #   container_name: sms-nginx
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./nginx
  #   ports:
  #     - "3050:80"
